### ISSUE TITLE
Why `DateTime` dependency?

### ISSUE THREAD

**Issue by bastantoine** [p0dalirius/pydsinternals#2]
Why do you need the [`DateTime`](https://pypi.org/project/DateTime/) module instead of the builtin `datetime`? And especially when you don't use it and overrides it with your own [`DateTime`](https://github.com/p0dalirius/pydsinternals/blob/main/dsinternals/system/DateTime.py) class... 😅

https://github.com/p0dalirius/pydsinternals/blob/69ff94b91b4cbf03df4ea0d3231d898781a0382f/requirements.txt#L2

The DateTime module specifically states that it probably shouldn't be used in most cases:

> This package provides a DateTime data type, as known from Zope. Unless you need to communicate with Zope APIs, you're probably better off using Python's built-in datetime module.

**Comment by p0dalirius** [comment]
It was a mistake, it's been removed from requirements. Thanks :+1:
