### ISSUE TITLE
KeyCredential Timestamp - OverflowError: date value out of range

### ISSUE THREAD

**Issue by sro-nviso** [p0dalirius/pydsinternals#4]
Hello, while using the tool pywhisker I was able to retrieve credential information from an AD environment.
There are two credentials linked to the account in question and for both the following Traceback is thrown:

> Traceback (most recent call last):
  File "/home/unprivileged/tools/pywhisker/pywhisker.py", line 824, in main
    shadowcreds.list()
  File "/home/unprivileged/tools/pywhisker/pywhisker.py", line 320, in list
    keyCredential = KeyCredential.fromDNWithBinary(DNWithBinary.fromRawDNWithBinary(dn_binary_value))
  File "/usr/local/lib/python3.9/dist-packages/dsinternals-1.2.4-py3.9.egg/dsinternals/common/data/hello/KeyCredential.py", line 233, in fromDNWithBinary
    _KeyCreationTime = ConvertFromBinaryTime(entry["data"], _KeySource, _Version)
  File "/usr/local/lib/python3.9/dist-packages/dsinternals-1.2.4-py3.9.egg/dsinternals/Utils.py", line 61, in ConvertFromBinaryTime
    return DateTime(timeStamp)
  File "/usr/local/lib/python3.9/dist-packages/dsinternals-1.2.4-py3.9.egg/dsinternals/system/DateTime.py", line 31, in __init__
    self.Value = datetime.datetime(1601, 1, 1, 0, 0, 0) + datetime.timedelta(seconds=ticks / 1e7)
OverflowError: date value out of range
[!] date value out of range

It seems the date is out of range, do you know by any chance how such a date could be included in the binary or how I could troubleshoot the issue?

Thanks a lot!

**Comment by p0dalirius** [comment]
Hi!

I'm sorry for looking into this only now.
Can you reproduce the issue or tell me how to reproduce it ?

Best regards,

**Comment by sro-nviso** [comment]
Hey!

No worries, as you can imagine my memories are sadly not this fresh anymore. 😄 
Thank you for getting back though!

AFAIK I was trying to retrieve the credential links from an account in the target environment and as you can see in the output above, the date time could not be parsed.
Sadly I do not have access to the environment in question anymore and the data has been deleted/encrypted according to our processes.

It was somehow possible to retrieve that there are two linked credentials for the accounts so I guess it only failed when trying to parse the timestamps.
I am not sure how the timestamp could have been "malformed" as even a time difference (lets say UTC and your current time is UTC+1) should result in a timestamp off by an hour but not results in the year 1601.

 As it failed here:
``` 
File "pywhisker/pywhisker.py", line 320, in list
keyCredential = KeyCredential.fromDNWithBinary(DNWithBinary.fromRawDNWithBinary(dn_binary_value))
```

I guess the problem could be a newer binary format that was not yet supported by the library "dsinternals" maybe?

**Comment by p0dalirius** [comment]
> _I guess the problem could be a newer binary format that was not yet supported by the library "dsinternals" maybe?_

I think you're right, it is probably an unsupported blob binary format, I'll try to fix it if I encounter it again, or please reopen this issue if you have the problem again.

Again, sorry for the response time.

**Comment by puzzlepeaches** [comment]
For the weary travelers that find their way here...

Edit `dsinternals/common/data/hello/KeyCredential.py` and modify line 233 from this:

```python
_KeyCreationTime = ConvertFromBinaryTime(entry["data"], _KeySource, _Version)
```

To this:

```python
            elif entry["entryType"] == KeyCredentialEntryType.KeyCreationTime.value:
                try:
                    _KeyCreationTime = ConvertFromBinaryTime(entry["data"], _KeySource, _Version)
                except OverflowError:
                    pass
```

I hope it brings you DA 🙏
