### ISSUE TITLE
Where did you find KeyMaterial structures?

### ISSUE THREAD

**Issue by CravateRouge** [p0dalirius/pydsinternals#6]
First I must say you did a great work with this module and it helps greatly to implement Shadow Credential in [bloodyAD](https://github.com/CravateRouge/bloodyAD), thanks a lot!

Second I'm currently doing some research on the keycredentiallink attribute and I was curious to know where you found KeyMaterial formats which can be found [here](https://github.com/p0dalirius/pydsinternals/blob/cc4585b1ba6998e44164360bd11f28c95cae6101/dsinternals/common/cryptography/X509Certificate2.py#L74) in your code. Because [KeyMaterial doc](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-adts/7185bc76-0518-4e72-9228-a7dceb751c41) doesn't tell anything. I tried the standard PKCS1 DER format but it didn't work but your RSAPublicKeyBCrypt do.

Did you find any docs on those formats?

**Comment by p0dalirius** [comment]
Hello,

Thank you!

Yes there is """documentation""" on it, although very sparse.

Firstly, the field `msDs-KeyCredentialLink` is a list containing DNWithBinary structures. (a ressource on this: http://www.ldapexplorer.com/en/manual/107070216-editor-ms-dnbinary.htm):

```
B:<rawDataLength>:<rawDatainHex>:<distinguishedName>
```

The `rawDatainHex` is a `RSAKeyMaterial` structure; defined here (https://docs.microsoft.com/en-us/windows/win32/api/bcrypt/ns-bcrypt-bcrypt_rsakey_blob). This RSAKeyMaterial binary blob is constructed like this:

![image](https://user-images.githubusercontent.com/79218792/212254411-88961785-aaf1-43df-bc14-2fa432674cf8.png)

Best regards,

## References
 - MS-ADA2: Attribute [msDS-KeyMaterial](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-ada2/1c9a25c0-d2b7-4741-ab34-c3a474b5da5a)
 - MS-ADA2: Attribute [msDS-KeyCredentialLink](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-ada2/45916e5b-d66f-444e-b1e5-5b0666ed4d66)
 - [Applying Cryptography Using The CNG API In Windows Vista](https://docs.microsoft.com/en-us/archive/msdn-magazine/2007/july/applying-cryptography-using-the-cng-api-in-windows-vista)
 - [RSAKeyMaterial binary blob](https://docs.microsoft.com/en-us/archive/msdn-magazine/2007/july/images/cc163389.fig11.gif)
 - http://www.ldapexplorer.com/en/manual/107070216-editor-ms-dnbinary.htm

**Comment by CravateRouge** [comment]
Thank you for those information and your quick reply :)

PS: The PKCS1 DER format works, I just needed some sleep and provide the right certificate for PKINIT x)

**Comment by p0dalirius** [comment]
I recently wrote an article on this format:

https://podalirius.net/en/articles/parsing-the-msds-keycredentiallink-value-for-shadowcredentials-attack/
